### ISSUE TITLE
DllNotFoundException

### ISSUE THREAD

**Issue by lyukstory** [airar-dev/Unity-AR-ColorMapping#24]
hi.

i just want to know about below Log Error when i push the shot button.

Log Error>
2021-07-15 01:23:35.236 6353 7026 Error Unity DllNotFoundException: Unable to load DLL 'AirarColorMap': The specified module could not be found.

so file that, libAirarColorMap.so , libopencv_java3.so  path are Assets/Plugins/Android/

please let me know about the solution.. thanks.

**Comment by AIRAR-JGS** [comment]
Hi,

Set the CPU to ARM64 in the platform settings of the libAirarColorMap.so file and the libopencv_java3.so file.


![1626312494374](https://user-images.githubusercontent.com/48006413/125713759-1a0719b3-df56-43c1-8f51-6cc20dded599.jpg)
![1626312510296](https://user-images.githubusercontent.com/48006413/125713764-22e326ab-3c1a-4d76-8835-d99f0bb38a0d.jpg)



thanks!
