### ISSUE TITLE
Color function does not work when shot button pressed (AR Foundation build)

### ISSUE THREAD

**Issue by kingbaggot** [airar-dev/Unity-AR-ColorMapping#25]
Color function not working - 

Using Unity 2020.3.9f1 
AR Foundation 4.1.7 
AR Core 4.17
Android build - on Google Pixel 2

I followed the steps detailed and on building the prefab appears and tracks correctly, but doesn't become coloured when the shot button is pressed. Instead the prefab disappears briefly and reappears as ARFoundationColorMapping.Play method is called.

*edit*
On looking closer It fails when calling  ImageProc(imgPath, src, height, width) in AirarManager. 
Is that a method in one of the java plugins ?

I was unable to use the recommend version of AR Foundation & AR Core as the AR subsystems for these version is not available on Unity 2020+ 
If I use an older version I can't build an apk the google play store will accept. 

Any help would be appreciated - thanks for creating this tool.

**Comment by AIRAR-JGS** [comment]
Try the Unity version and AR engine version listed in Readme.

We will soon update the library by testing it on the latest version of Unity and AR engine.

Thanks!
