### ISSUE TITLE
DllNotFound : AirarColorMap

### ISSUE THREAD

**Issue by TiagoFerreiraDomingues** [airar-dev/Unity-AR-ColorMapping#27]
**Describe the bug**
Hello,
Today I have a problem, despite having browsed all the forums tried all the solutions, I do not know for what reason, the AiraColorMap library is not recognized...
How to do ?

**Screenshots**
![image](https://user-images.githubusercontent.com/73883485/154826327-528dc0f2-0abb-44fe-8b72-d26072d669fd.png)

**Desktop (please complete the following information):**
 - OS: [Windows 11]
 - Unity ; 2021.2.12f
 - Vuforia : 9.3.3 (if use newest, project don't find FinderTaget class)

**Comment by airar-dev** [comment]
The warning in the image is that the library is not recognized by the Unity editor. The AiraColorMap library does not work in the editor because it works only when building Android or iPhone.
By any chance, the library is not recognized even if you build with iPhone or Android?

**Comment by TiagoFerreiraDomingues** [comment]
Hello, I have actually tried what you suggest and it doesn't work either.
Do we agree that it should be imported into the new asset tab?

**Comment by airar-dev** [comment]
Hello

I need more detailed information to solve the problem.

First of all, is it not even possible to build on Android or iOS platforms in Unity?

Or, the build works, but an error occurs?

If there is an error can you show the error log?

**Comment by TiagoFerreiraDomingues** [comment]
Hello,
So the build works perfectly, the detection of my 3D models via the ImageTarget also goes well, but when I press "SHOT" it tries to call Imgproc but as it does not find AirarColorMap (the libairarcolormap.so file), it gives me an exception "DLL Not Found". 
![image](https://user-images.githubusercontent.com/73883485/155692243-ac447338-9254-46a5-a97a-199079459518.png)

**Comment by airar-dev** [comment]
Please make sure that the libopencv_java3.so file is also included in the
project.

And set the cpu of the libAirarColorMap.so file and libopencv_java3.so file
included in the project to 64-bit.

**Comment by TiagoFerreiraDomingues** [comment]
Both files are well in plugin/android libaircolormap.so is the latest version you provided, for libopencv_3.so I downloaded the latest update of open cv 3 (3.4.7 from memory).
And both have been modified in ARM64
How can I see if my project is 64 bits?

**Comment by airar-dev** [comment]
How to set up a project is described in detail in Readme.

For project 64-bit settings, just check ARM64 in Player Settings > Android > target architectures.

And you need to use opencv version 3.4.11 as described in readme.
