### ISSUE TITLE
plugin doesnt work with vuforia version 10.0 and above

### ISSUE THREAD

**Issue by lthea** [airar-dev/Unity-AR-ColorMapping#30]
Hi, I tried using this plugin with Vuforia version 10.11 but I got a namespace error for the Vuforia function. So is there any way to fix this using the latest version of Vuforia? Really hope to resolve this soon, Thank You ..

**Comment by airar-dev** [comment]
I will update the sample soon to be compatible with the latest version of Vuforia.
Please wait a moment.

**Comment by lthea** [comment]
ok Thank You, Sir

**Comment by airar-dev** [comment]
I just uploaded a sample created using the 10-11-3 version of the Vuforia SDK.
I used the 2021.3.2f1 version of Unity.

Thanks for waiting.

**Comment by lthea** [comment]
omg, thank you so much. I really need this for my school project. Really appreciate it 👍
