### ISSUE TITLE
DllNotFoundException: AirarColorMap assembly:<unknown assembly> type:<unknown type> member:(null) i get the error

### ISSUE THREAD

**Issue by ahmetKaya00** [airar-dev/Unity-AR-ColorMapping#31]
I am getting this error even though I have done all the steps. Please help with this. I have to complete homework. Thank you from now.

Unıty: 2021.3.11f1
Libopencv_java4.so
vuforıa SDK: add-vuforia-package-10-12-3 
Android

![1](https://user-images.githubusercontent.com/115210242/210612396-1517c8c9-c57c-406d-9026-ec20e98496c8.png)
![2](https://user-images.githubusercontent.com/115210242/210612402-84469fb0-d11e-4a16-ba19-6a4b234fcf67.png)
![3](https://user-images.githubusercontent.com/115210242/210612403-2595b672-3117-4a94-b623-3e8b4e662f04.png)
![4](https://user-images.githubusercontent.com/115210242/210612390-ff30f67c-cacb-422a-8026-4df17c61afbe.png)
![5](https://user-images.githubusercontent.com/115210242/210613667-ee5abb9d-247d-487f-85d8-2d131200a720.png)

**Comment by AIRAR-JGS** [comment]
libopencv_java3.so file and libAirarColorMap.so file
It should be placed inside the Assets/Plugins/Android folder.

![1672900623140](https://user-images.githubusercontent.com/48006413/210717510-8ed48ca7-5cb3-4c3e-863d-70517ab5864a.jpg)

**Comment by ahmetKaya00** [comment]
I did everything but still getting this error. Please help me.
![6](https://user-images.githubusercontent.com/115210242/210754303-f21d8e2a-4394-4de1-9377-8accaf01c8f1.png)
![Ekran görüntüsü 2023-01-05 130655](https://user-images.githubusercontent.com/115210242/210754648-ccc28a1a-455a-4660-89c8-8ad12db830f8.png)
I did everything but still getting this error. Please help me.
Android studio and opencv are not installed on my computer, could this be the reason?
If you give your Instagram address, we can talk in more detail.

**Comment by AIRAR-JGS** [comment]
[https://github.com/airar-dev/Unity-AR-ColorMapping/issues/29#issuecomment-1315085990](https://github.com/airar-dev/Unity-AR-ColorMapping/issues/29#issuecomment-1315085990)

There is a demo video in the link above.

**Comment by Jamedie** [comment]
Hello, I have the same issue with this specs, did you find a solution?
Unıty : 2021.3.15f1 & 2021.3.2f1
Libopencv_java4.so or Libopencv_java3.so
Vuforıa : 
10.12.3 + package 1.3.2
10.11.3 + package 1.3.2
9.8.13 + package 1.3.1
Android 

ArFoundation : work fine
Thanks for your time.

**Comment by AIRAR-JGS** [comment]
Unity 2021.3.4f1, Vuforia 10.11.3 + package 1.3.2 and libopencv_java3 works fine..
I think you're missing something...

Have you put both the libopencv_java3.so file and the libAirarColorMap.so file and set them to ARM64?

Make sure you set the define correctly
