### ISSUE TITLE
webAR Support 

### ISSUE THREAD

**Issue by Ichtestenurmal** [airar-dev/Unity-AR-ColorMapping#32]
Hello, 

I would love to work and experiment with your code, is there any way to get this working with WebAR in the meantime?

I would be very happy about an answer

**Comment by AIRAR-JGS** [comment]
Hello

Unfortunately, there are no plans to support the web platform for the time being.

I'll let you know when I develop a library for web platforms in the future!

Thank you.

**Comment by Ichtestenurmal** [comment]
Is there anything I can do to help you with that?
Unfortunately I can't find any other way to use the technique for WEBAR I want to create a coloring book.

**Comment by AIRAR-JGS** [comment]
Hello

Unfortunately, there are no plans to support the web platform for the time being.
