### ISSUE TITLE
pls make a video for ios build too......

### ISSUE THREAD

**Issue by vishal19x** [airar-dev/Unity-AR-ColorMapping#34]
pls make a video for ios build too......
Completed all steps but still getting error in xcode...

used opencv2.framework file version 3.4.11.
downloaded from here. [https://sourceforge.net/projects/opencvlibrary/files/3.4.11/]

errors....
Showing Recent Issues
Undefined symbol: MatToUIImage(cv::Mat const&)
Showing Recent Issues
Undefined symbol: UIImageToMat(UIImage const*, cv::Mat&, bool)
Showing Recent Issues
Undefined symbol: cv::warpPerspective(cv::_InputArray const&, cv::_OutputArray const&, cv::_InputArray const&, cv::Size_<int>, int, int, cv::Scalar_<double> const&)
Showing Recent Issues
Undefined symbol: cv::getPerspectiveTransform(cv::Point_<float> const*, cv::Point_<float> const*)
Showing Recent Issues
Undefined symbol: cv::Mat::deallocate()
Showing Recent Issues
Undefined symbol: cv::fastFree(void*)

working completely fine in android but not in ios..

vuforia version 10.13.3
unity version 21.3.11f1

_Originally posted by @vishal19x in https://github.com/airar-dev/Unity-AR-ColorMapping/issues/29#issuecomment-1489801678_

**Comment by vishal19x** [comment]
use opencv2.framework file version 4.7.0
it work's completely fine for me.

thanks.

**Comment by Simon1Asmar** [comment]
I'm still getting the same errors with iOS even on version 4.7.0 of opencv2

vuforia version 10.13.3
unity version 2021.3.8f1

When you click on the opencv2.framework or the LibAirarColorMap.a do you have anything checked also is the CPU set to ARM64 for both?

Can you also tell me or send me a screenshot showing the things in the build settings / player settings?

**Comment by vishal19x** [comment]
![Screenshot 2023-09-20 191134](https://github.com/airar-dev/Unity-AR-ColorMapping/assets/121216788/747e106c-6ab4-4b5d-93ab-b02cbd8be86a)

![Screenshot 2023-09-20 191323](https://github.com/airar-dev/Unity-AR-ColorMapping/assets/121216788/973ea446-7d87-4c3b-8821-a1a633ca986d)

![Screenshot 2023-09-20 191358](https://github.com/airar-dev/Unity-AR-ColorMapping/assets/121216788/bfce19e1-4e09-44ca-b406-a88b5d1d030d)
