### ISSUE TITLE
Model texturing

### ISSUE THREAD

**Issue by Holeric** [airar-dev/Unity-AR-ColorMapping#37]
**Describe the bug**
I'm just curious to see if you can get some guidance on marker design. Since the texture of the model depends on the quality of the marker, I want to understand how to do it correctly. I attached screenshots of my marker and model here. There, for example, you can see that there is a black stripe on the back and other defects.

**Screenshots**

![photo_2023-07-25_02-07-23](https://github.com/airar-dev/Unity-AR-ColorMapping/assets/33574424/7b1915ea-e684-44fd-8531-a013c1890a3b)
![photo_2023-07-25_02-07-11](https://github.com/airar-dev/Unity-AR-ColorMapping/assets/33574424/3b6aec7c-c5df-458a-bdb7-f4d9399bae3f)
![photo_2023-07-25_02-06-59](https://github.com/airar-dev/Unity-AR-ColorMapping/assets/33574424/653af7ec-dba9-472f-87c2-788445348c4e)
![photo_2023-07-25_02-06-44](https://github.com/airar-dev/Unity-AR-ColorMapping/assets/33574424/a2721afe-91c5-4e10-86fa-7d790b059a27)
![photo_2023-07-25_02-06-42](https://github.com/airar-dev/Unity-AR-ColorMapping/assets/33574424/d7e34d7b-984d-45e8-af86-8bd93153427a)
![photo_2023-07-25_02-06-29](https://github.com/airar-dev/Unity-AR-ColorMapping/assets/33574424/3aac9775-7f67-481d-8655-b767de8bc7c1)

**Comment by Holeric** [comment]
Marker here

![dino — копия](https://github.com/airar-dev/Unity-AR-ColorMapping/assets/33574424/a35bd4e3-d2b5-47fb-b4c3-4f3d2ed30c61)

**Comment by AIRAR-JGS** [comment]
I made a video guide on how to create 3D. Please refer to the [link](https://youtu.be/2-h8aBLddjY).
