### ISSUE TITLE
DllNotFoundException: AirarColorMap assembly:<unkown assembly> type:<unknown type> member:(null) 

### ISSUE THREAD

**Issue by Akairojhon** [airar-dev/Unity-AR-ColorMapping#38]
**Describe the bug**
When I click on the button "Shot", this error pops up. I have tried everything i have seen in the others issues posts. 

**To Reproduce**
1. In PlayMode
2. Pressing the "Shot" button

**Expected behavior**
The model should change it's colour

**Screenshots**
![image](https://github.com/airar-dev/Unity-AR-ColorMapping/assets/147447157/374e8687-92e1-4654-8f7a-2c6d6777c1ba)
![image](https://github.com/airar-dev/Unity-AR-ColorMapping/assets/147447157/604fa733-cad0-4c87-965e-4005b845fec7)

**Additional context**
I think the problem is I haven't installed the openCV stuff but, in the Youtube tutorials it is not installed. Though, i don't know how to install it.

I am using>
Unity 2022.3.8
Vuforia 10.18.4

**Comment by AIRAR-JGS** [comment]
This library only works with Android or iPhone.

Unable to run in Unity Editor.
It must be built and run on a real Android or iPhone device.
