### ISSUE TITLE
ld: warning: ignoring duplicate libraries: '-lc++' ld: Undefined symbols: MatToUIImage(cv::Mat const&), referenced from:

### ISSUE THREAD

**Issue by muratunlu0** [airar-dev/Unity-AR-ColorMapping#39]
I got this error while building with Xcode in Unity.
![WhatsApp Image 2023-10-28 at 18 07 36](https://github.com/airar-dev/Unity-AR-ColorMapping/assets/18752325/dfc3841f-7ead-477c-8cfe-73bbd1966463)

**Comment by AIRAR-JGS** [comment]
This error cannot be reproduced.

I need a little more information about the environment where the error occurred.
Can I know the Unity version, Xcode version, and opencv version used?
