### ISSUE TITLE
Model Texturing

### ISSUE THREAD

**Issue by Holeric** [airar-dev/Unity-AR-ColorMapping#40]
I just want to ask. Do you think it is possible to achieve better quality for this model or not? If not, then I would like to understand what are the restrictions when creating models so that the texture fits best?

I will attach some links below with videos so you can evaluate my results:
1) https://drive.google.com/file/d/15lNXzpnXoeqgbFi86hw31DK0akfMcMMk/view?usp=sharing
2) https://drive.google.com/file/d/1DrQ5_PUcHpG1dWw8GmvUw0AiciQ4JTAx/view?usp=sharing
3) https://drive.google.com/file/d/1fPco70pImRz8ysP3tzDjBFc4Zp_bl8E7/view?usp=sharing

Based on the results I got, I think I was lucky to get a couple of good shots, but overall there was a lack of consistency.

If you need my model and marker for testing, I can send you a link.

**Comment by airar-dev** [comment]
https://youtu.be/2-h8aBLddjY

Please refer to the YouTube link above for 3D production.
