### ISSUE TITLE
Undefined Symbols on iOS build using ARFoundation

### ISSUE THREAD

**Issue by fourthedesign** [airar-dev/Unity-AR-ColorMapping#41]
**Describe the bug**
I have a project in Unity that uses Arfoundation and Airar. I successfully built for android, but when transferring to XCode and building for a device I received the following errors:
Undefined symbol: MetToUIImage(cv::Matconst&)
Undefined symbol: UIImageToMat(UIImageconst& cv::Mat& bool)
Undefined symbol: cv::warpPerspective(..)
Undefined symbol: cv::gtePerspectiveTransform(...)
Undefined symbol: cv::Mat::deallocate()
Undefined symbol: cv::fastFree(void*)
Which seems to be Linker connected error

**To Reproduce**
1. Copied libAirarColorMap.a and opencv2.framework (v3.4.11 as suggested) to Plugins/iOS in Unity 
2. Set the appropriate settings in Player Settings as suggested in Readme
3. target iOs Version 11+
4. Built for iOS and opened in XCode
5. Built for iOS device
6. Build failed with the above errors. 

**Desktop (please complete the following information):**
 - Unity 2022.3.6
 - ArFoundation 5.0.7
 - ARKit 5.0.7
 - XCode 14.3 

**Additional context**
What we tried: 
1. setting opencv2.framework to "Embed&Sign" in Xcode Frameworks and Libraries
2. Setting Library Search Paths and Header Search Paths to opencv2.framework
3.  Clean build folder in XCode

**Comment by arif69eee** [comment]
Hi @fourthedesign ,

Were you able to fix this issue? Please let us know if you were, it would be very helpful !! I am also getting the same error!

Author of this plugin, would you please help us?

Many thanks!

**Comment by airar-dev** [comment]
I think it's a lower version of Unity issue.

Distributed a new version of the ARFoundation sample project.
Try the Unity 2023.2.0f1 version.
