### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by jdgrana2** [airar-dev/Unity-AR-ColorMapping#42]
I followed all the steps, now I downloaded the opencv that you mention in the step by step, initially it had many errors but everything is correct after watching the video several times and seeing each configuration you had, I am working on uniy 2022.3.39

I already have the APK, but when I use the camera to see the image / marker nothing comes out, the astronaut does not appear, I want to know if I need to do something with the prefab or something additional that is missing, I also created a sphere, I put a copy of the material with the shader you have in the project, I put the "coloring" tag and I created an image almost the same as the astronaut but with a circle,  I saved it in bookmarks and streamingassets, and included it in the ReferenceImageLibrary.  But none of the markers work

I tried it on a Samsung Galaxy note 20

And one last question if the printed image is smaller and I don't change the values in the ReferenceImg there is any problem, just to make tests or if I do it from a pc monitor to paint the image from photoshop it could.

**Comment by AIRAR-JGS** [comment]
I need an error log to figure out the cause of the problem.

**Comment by airar-dev** [comment]
no more info
